### ISSUE TITLE
speech speed

### ISSUE THREAD

**Issue by chiaki-luo** [unilight/seq2seq-vc#14]
Dear author, it sounds like the decoding results of Stage 6 are faster than those of Stage 4.  How could I fix the problem?

**Comment by unilight** [comment]
Hi @chiaki-luo , can you tell me what recipe you are running? Also it would be helpful if you can attach samples.

**Comment by chiaki-luo** [comment]
Thank you for your response @unilight. I run the L2-arctic recipe. It seems that the performance of the VC model has something wrong.
[conversion.zip](https://github.com/unilight/seq2seq-vc/files/15256812/conversion.zip)

**Comment by unilight** [comment]
Hi @chiaki-luo which recipe under l2-arctic are you running?

**Comment by chiaki-luo** [comment]
@unilight cascade

**Comment by unilight** [comment]
Hi @chiaki-luo, I noticed that in the zip file you attached, the `stage6_arctic_b0440.wav` file has a sampling rate of 24kHz. Can you tell me how you generated that sample? If you used the PWG I provided, it should generate 16kHz outputs.

**Comment by chiaki-luo** [comment]
I skip the evaluatiuon, just run ./run.sh --stage 4 --stop_stage 4 and ./run.sh --stage 6 --stop_stage 6. Is there any hparam setting for the sampling rate of generation?

**Comment by unilight** [comment]
Can you show me this file: `exp/TXHC_bdl_1032_vtn.tts_pt.v1/results/checkpoint-50000steps/stage2_ppg_sxliu_checkpoint-50000steps_TXHC_dev/decode.log`? (This is the log of the stage 2 decoding)

**Comment by chiaki-luo** [comment]
@unilight I downloaded the ckpt from huggingface manually, maybe I downloaded a wrong ckpt?
[decode.log](https://github.com/unilight/seq2seq-vc/files/15257656/decode.log)

**Comment by unilight** [comment]
From `decode.log` I see you are using `/media/hello/xiaolan_T7/seq2seq-vc-main/egs/l2-arctic/cascade/downloads/hifigan/checkpoint-2500000steps.pkl` which is a HiFiGAN vocoder. I don't think I provided a HiFiGAN vocoder... where did you download it? Please run stage -1. The script automacially downloads all the pre-trained models.

**Comment by chiaki-luo** [comment]
@unilight Thank you for your help. It's my bad for a vocoder change. I appreciated it.
