### ISSUE TITLE
Process for training the three techniques described by any source speaker. 

### ISSUE THREAD

**Issue by PAAYAS** [unilight/seq2seq-vc#15]
Hello, @unilight As part of my work on the LSC model, I want to convert the accent of an other speaker—let's say ASI from the L2ARCTIC dataset—to BDL (the target). The pretrained models that you have provided appear to have been trained using TXHC speakers. Could you give us a thorough training approach so we can train the non-parallel frame-based VCF model or vocoders on any source speakers? 

I look forward to hearing from you as soon as possible. I'm grateful.

**Comment by PAAYAS** [comment]
If you could assist me with training the LSC or cascade model for a different source speaker, that would be greatly appreciated.

**Comment by unilight** [comment]
Hi @PAAYAS, can you try to follow the instructions in the readme here: https://github.com/unilight/seq2seq-vc/tree/main/egs/l2-arctic/lsc, and then see if you have any problem? If you only want to convert "from" a new speaker, it's actually quite simple -- you only need to train the seq2seq model. (If you want to convert "to" a new speaker it's much more troublesome.)

**Comment by PAAYAS** [comment]
Hello @unilight I used an ASI speaker to train the LSC model, and I set the target to BDL. The voice of the TXHC speaker appeared in the wav files that were produced during the decoding process, rather than the ASI speaker. Could you let me know if want to train any other models with ASI speaker. Thank you.

**Comment by PAAYAS** [comment]
[ASI_BDL_LSC.zip](https://github.com/user-attachments/files/15982166/ASI_BDL_LSC.zip)
Here by I am providing some of the results which I obtained while decoding.

**Comment by unilight** [comment]
@PAAYAS The current methods (all three) cannot convert from a specific new speaker without re-training (or fine-tuning) using the data from that new speaker.

**Comment by PAAYAS** [comment]
@unilight I see now. Could you could assist me with how to fine-tune for a new speaker or retrain models?

**Comment by unilight** [comment]
@PAAYAS Please try to follow the instructions in the readme here: https://github.com/unilight/seq2seq-vc/tree/main/egs/l2-arctic/lsc.

**Comment by PAAYAS** [comment]
@unilight Thank you, will look once again.

**Comment by PAAYAS** [comment]
Greetings, @unilight. As you indicated in https://github.com/unilight/seq2seq-vc/tree/main/egs/l2-arctic, you are employing the [S3PRL-VC](https://github.com/unilight/s3prl-vc) toolbox for non-parallel frame-based VC model training. Could you please help me with my own dataset training?

**Comment by unilight** [comment]
You can try to follow the instructions at https://github.com/unilight/s3prl-vc/tree/main/egs/TEMPLATE/a2o_vc.

**Comment by PAAYAS** [comment]
Hello @unilight, thank you for your time, I was able to train the non-parallel frame-based VC model on my dataset, but the waveform produced while decoding seems not capturing speaker identity. Could you help me on how we can train the **vocoder** model on any **source speaker**?

**Comment by PAAYAS** [comment]
Greetings, @unilight Could you please provide me with instructions on how to convert an accent from multiple speakers to one target speaker?

**Comment by unilight** [comment]
It's not quite possible with the functions provided in this repo.
