### ISSUE TITLE
LSC : Inference problem

### ISSUE THREAD

**Issue by Fbarrade** [unilight/seq2seq-vc#16]
Hellon, i read the steps described in lsc folder but i didnt really understand how to infer this model , i wanna just do the inference of a pretained model . Can you please  explain to me the steps that i should follow ;? 
Thanks in advance

**Comment by unilight** [comment]
Hi @Fbarrade, currently for the accent conversion recipes, we don't support pre-trained models thus it's not possible to do pure inference now. You can however train the model by yourself.

Also note that all models we support are one-to-one voice conversion, i.e. the model can only convert from one particular source speaker to one particular target speaker (that is to say, the source and target speakers seen during training)

Based on the above reason, the main purpose of the accent conversion recipes is for research reproducibility. If you are looking for a model that can de-accent any input voice from an arbitrary speaker, then this repo may not suit your needs... :(
