### ISSUE TITLE
ModuleNotFoundError: No module named 'seq2seq_vc.vocoder.encodec'

### ISSUE THREAD

**Issue by MohanThippeswamy** [unilight/seq2seq-vc#2]
I'm getting following error after running ./run.sh  --stage 4 --stop stage 5 --tag <>
ModuleNotFoundError: No module named 'seq2seq_vc.modules.diffsinger'
ModuleNotFoundError: No module named 'seq2seq_vc.vocoder.encodec'

Did I miss any dependent packages..

**Comment by unilight** [comment]
Hi @MohanThippeswamy, sorry it was a mistake when I was cleaning up the code. For now, you can just delete these two lines: https://github.com/unilight/seq2seq-vc/blob/81cbce1cfe8224d50fe5b71eef332bc6eb6b34b5/seq2seq_vc/models/aas_vc.py#L34-L35. I'll push an updated commit as soon as possible. Thanks again for spotting this!!

**Comment by MohanThippeswamy** [comment]
Great! 
I just commented those two lines and relevant code.
