### ISSUE TITLE
RuntimeError: The size of tensor a (144) must match the size of tensor b (80) at non-singleton dimension 1

### ISSUE THREAD

**Issue by MohanThippeswamy** [unilight/seq2seq-vc#3]
Getting error with vocoder... 
c = (c - self.stats["mean"]) / self.stats["scale"]
RuntimeError: The size of tensor a (144) must match the size of tensor b (80) at non-singleton dimension 1

I'm using pretrained models
pwg_TXHC/checkpoint-400000steps.pkl

**Comment by unilight** [comment]
Hi @MohanThippeswamy, can you tell me which recipe you are running?

**Comment by unilight** [comment]
Ah, I guess you are running the `egs/l2-arctic/lsc` recipe, and I think I know what the problem is... please give me some time to solve it. Sorry for this inconvenience!

**Comment by MohanThippeswamy** [comment]
you are right its egs/l2-arctic/lsc recipe. 
Appreciate your turn around on the comments

Thanks

**Comment by MohanThippeswamy** [comment]
> Ah, I guess you are running the `egs/l2-arctic/lsc` recipe, and I think I know what the problem is... please give me some time to solve it. Sorry for this inconvenience!

@unilight, after using latest fixes  the problem still remains the same (RuntimeError: The size of tensor a(144) must match the size of tensor b(80) at non-singleton dimension)

**Comment by unilight** [comment]
Hi @MohanThippeswamy can you tel me which step it is and maybe the whole log?

**Comment by MohanThippeswamy** [comment]
Hi @unilight, I was trying LSC inferencing using pretrained models 

# pretrained model related
pretrained_model_checkpoint=downloads/ljspeech_text_to_ppg_sxliu_aept/checkpoint-50000steps.pkl
npvc_checkpoint=downloads/s3prl-vc-ppg_sxliu/checkpoint-50000steps.pkl
npvc_name=ppg_sxliu

Please find log below
Stage 4: Network decoding
Decoding start. See the progress via exp/TXHC_bdl_1032_trial2_tm/results/checkpoint-50000steps/TXHC_dev/decode.*.log.
Decoding start. See the progress via exp/TXHC_bdl_1032_trial2_tm/results/checkpoint-50000steps/TXHC_eval/decode.*.log.
run.pl: 16 / 16 failed, log is in exp/TXHC_bdl_1032_trial2_tm/results/checkpoint-50000steps/TXHC_eval/decode.*.log
run.pl: 16 / 16 failed, log is in exp/TXHC_bdl_1032_trial2_tm/results/checkpoint-50000steps/TXHC_dev/decode.*.log

**Comment by MohanThippeswamy** [comment]
**cont...** 
 with open(config) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/group1/z44476r/Experiments/s3prl-vc/egs/ljspeech/a2o_vc/exp/ppg_sxliu_taco2_ar/config.yml'

**Comment by unilight** [comment]
@MohanThippeswamy did you execute stages 0 to 3? The pre-trained models are used in the training, not for direct inference. 

> **cont...** with open(config) as f: FileNotFoundError: [Errno 2] No such file or directory: '/data/group1/z44476r/Experiments/s3prl-vc/egs/ljspeech/a2o_vc/exp/ppg_sxliu_taco2_ar/config.yml'

In my last fix, I added some instructions on modifying the paths in the config file. Please check.

**Comment by MohanThippeswamy** [comment]
@unilight,  I executed stages 0to 2 but not 3. 
 your instruction from last fix  is for conf/config.yml right? Bu anyway I have applied for all the models.

Pretrained models are not for direct inference. got it.  
Wanted to use your pretrained models directly for inference where do I get those final models. please share the link that will help.

**Comment by MohanThippeswamy** [comment]
updating last fix (removed diifsinger module) is impact training..
ModuleNotFoundError: No module named 'seq2seq_vc.losses.diffsinger_l2_loss'.
 So I'm struck at training so, I tried direct inferencing

**Comment by MohanThippeswamy** [comment]
@unilight,
any updates and further wanted to check on pretrained models?

**Comment by unilight** [comment]
Hi @MohanThippeswamy, sorry I'm a bit occupied these days. Will get back to you today!

**Comment by unilight** [comment]
@MohanThippeswamy See #[36554fa](https://github.com/unilight/seq2seq-vc/commit/36554fa74e4ab8002c661f43db5c1287d93c2e63)

**Comment by MohanThippeswamy** [comment]
@unilight  Thanks!
#[36554fa]  I verified lsc with pretrained models updates are working.

**Comment by unilight** [comment]
Cool!
