### ISSUE TITLE
many-to-one conversion

### ISSUE THREAD

**Issue by chiaki-luo** [unilight/seq2seq-vc#7]
Dear author, thank you for your great work!
It seems that the FAC experiments is one-to-one accent conversion. Could you teach me that how can I set the program to train with several speakers who have different accents while the target speaker is bdl?
Thank you very much!

**Comment by unilight** [comment]
Hi, sorry for this super late response.
You are correct that the current implementation only supports one-to-one accent conversion and cannot convert from unseen speakers.
I once thought about implementing the zero-shot method in this paper: https://www.isca-archive.org/interspeech_2022/quamer22_interspeech.pdf, but did not have the capacity... :(
